name: archive2
version: 3.1.2
description: >-
  Provides encoders and decoders for various archive and compression formats
  such as zip, tar, bzip2, gzip, and zlib.
repository: https://github.com/brendan-duncan/archive
environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  path: ^1.8.0-0

dev_dependencies:
  extra_pedantic: ^1.4.0
  test: ^1.16.0-nullsafety.15
